select * from cus limit 20;

ALTER TABLE cus
ADD COLUMN age_group TEXT;

UPDATE cus
SET age_group = CASE
    WHEN age < 25 THEN 'Young Adult'
    WHEN age BETWEEN 25 AND 39 THEN 'Adult'
    WHEN age BETWEEN 40 AND 59 THEN 'Middle-Aged'
    WHEN age >= 60 THEN 'Senior'
END;


select * from cus;


--1. What is the total revenue generated by males vs. female customers?
select gender,sum(purchase_amount) as Total_Revenue
from customer
group by gender;

--2.Which customers used a discount but stilll spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >=(select avg(purchase_amount) from customer);

--3.Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


--4.Compare the average purchase amounts between standard and express shipping?
select shipping_type,round(avg(purchase_amount::numeric),2) as "Average purchase amount" from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--5.Do subscribed customers spend more? compare average spend and total revenue between subscribers and non subscribers?
select subscription_status,
count(customer_id) as "Total customer",
round(Avg(purchase_amount::numeric),2) as avg_spend,
round(sum(purchase_amount::numeric),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--6.Which 5 products have the highes percentge of purchse with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--7.Segment customers into new,returning and loyal based on their total number of previous purchases and show the count of each segment?
with customer_type as(
select customer_id,previous_purchases,
case
    when previous_purchases =1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as  customer_segment
from customer
)
select customer_segment,count(*) as "Number of  Customers"
from customer_type
group by customer_segment


--8. what are the top 3 most purchsed products within each category?

with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

--9.Are customers who are repeat buyers more than 5 previous purchaases also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status


--10. what is the revenue by age group?
select age_group,
sum(purchase_amount) as total_revenue
from cus
group by age_group
order by total_revenue desc;











-- for to create header in proper way
DO $$
DECLARE
    rec RECORD;
    new_col TEXT;
BEGIN
    FOR rec IN
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public'         -- change schema if needed
          AND table_name = 'cus'  -- 🔹 replace this
    LOOP
        -- create snake_case: lowercase + replace non-alphanumeric with underscore
        new_col := lower(regexp_replace(rec.column_name, '[^a-zA-Z0-9]+', '_', 'g'));

        -- remove trailing underscores (if any)
        new_col := regexp_replace(new_col, '_+$', '');

        -- only rename if different
        IF rec.column_name <> new_col THEN
            RAISE NOTICE 'Renaming "%" → "%"', rec.column_name, new_col;
            EXECUTE format(
                'ALTER TABLE public.%I RENAME COLUMN "%s" TO %I;',
                'cus', rec.column_name, new_col
            );
        END IF;
    END LOOP;
END $$;






--for to convert lower case
DO $$
DECLARE
    r RECORD;
    old_name TEXT;
    new_name TEXT;
BEGIN
    FOR r IN
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public'      -- Change if your table is in another schema
          AND table_name = 'cus'   -- 🔹 Replace with your actual table name
    LOOP
        old_name := r.column_name;
        new_name := lower(r.column_name);

        -- Only rename if the name isn't already lowercase
        IF old_name <> new_name THEN
            EXECUTE format(
                'ALTER TABLE public.%I RENAME COLUMN %I TO %I;',
                'cus', old_name, new_name
            );
        END IF;
    END LOOP;
END $$;

ALTER TABLE cus
RENAME COLUMN "purchase_amount_usd" TO purchase_amount;

select * from cus limit 20;

